version: '3.8'

services:
  mongo:
    image: mongo:6
    container_name: nomadly-mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  app:
    image: tayaa1/nomadly-backend:latest
    container_name: nomadly-backend
    restart: always
    depends_on:
      - mongo
    ports:
      - "3005:3000"
    environment:
      - MONGODB_URI=mongodb://mongo:27017/nomadly
      - NODE_ENV=production
      # Email configuration
      - MAIL_HOST=smtp.gmail.com
      - MAIL_PORT=587
      - MAIL_SECURE=false
      - MAIL_USER=nomadly.app2025@gmail.com
      - MAIL_PASSWORD=jqkh skhy ldqy nkuo
      - MAIL_FROM="Nomadly App" <nomadly.app2025@gmail.com>
      # Other env vars as needed

  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    restart: always
    environment:
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_POLL_INTERVAL=300
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - app
    env_file:
      - .env

volumes:
  mongo_data:
